
name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

deploy-dev:

    runs-on: ubuntu-latest
    environment:
    name: dev
    url: 'venalu.com.br'
    needs: build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploy DEV
        
deploy-hmg:
 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
    name: hmg
    url: 'venalu.com.br'
    needs: deploy-dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploy HMG
        
deploy-prod:
 
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment:
    name: prod
    url: 'venalu.com.br'
    needs: deploy-hmg

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Deploy PROD        
